name: workiom_signup
description: Workiom multi-step tenant sign-up flow.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  bloc_concurrency: ^0.3.0
  dartz: ^0.10.1
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^10.0.0
  flutter_svg: ^2.0.9
  flutter_timezone: ^4.1.1
  freezed_annotation: ^3.1.0
  get_it: ^9.2.1
  go_router: ^17.2.1
  intl: ^0.20.0
  json_annotation: ^4.11.0
  pretty_dio_logger: ^1.4.0
  rxdart: ^0.28.0

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.7
  flutter_gen_runner: ^5.10.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.5
  json_serializable: ^6.7.1
  mocktail: ^1.0.1
  very_good_analysis: ^10.2.0

flutter_gen:
  output: lib/core/gen/
  line_length: 80
  assets:
    enabled: true
    outputs:
      class_name: Assets
      package_parameter_enabled: false
  fonts:
    enabled: false
  colors:
    enabled: false

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik/Rubik-Medium.ttf
          weight: 500
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
